### ISSUE TITLE
spec cpu 2006 issues on ARM

### ISSUE THREAD

**Issue by regehr** [AbsInt/CompCert#154] opened 2016-12-11 01:22 UTC
Has anyone else tried running SPEC CPU 2006 on ARMv7 lately? I'm using the master branch of CompCert as of today on a Raspberry Pi 3 running a fully updated Raspbian Jessie.

I'm getting compare failures from both 464.h264ref and 482.sphinx3, see output sample below. I see very similar mismatches when compiling the benchmarks with GCC 4.9.2 and GCC 6.2.1, so perhaps there's an issue in the C library on this platform. Anyway, just curious if anyone has looked into this.

```
Running Benchmarks
  Running (#1) 429.mcf ref base jdr default
/home/pi/cpu2006-1.2/bin/specinvoke -d /home/pi/cpu2006-1.2/benchspec/CPU2006/429.mcf/run/run_base_ref_jdr.0001 -e speccmds.err -o speccmds.stdout -f speccmds.cmd -C -q
/home/pi/cpu2006-1.2/bin/specinvoke -E -d /home/pi/cpu2006-1.2/benchspec/CPU2006/429.mcf/run/run_base_ref_jdr.0001 -c 1 -e compare.err -o compare.stdout -f compare.cmd
  Running (#1) 456.hmmer ref base jdr default
/home/pi/cpu2006-1.2/bin/specinvoke -d /home/pi/cpu2006-1.2/benchspec/CPU2006/456.hmmer/run/run_base_ref_jdr.0001 -e speccmds.err -o speccmds.stdout -f speccmds.cmd -C -q
/home/pi/cpu2006-1.2/bin/specinvoke -E -d /home/pi/cpu2006-1.2/benchspec/CPU2006/456.hmmer/run/run_base_ref_jdr.0001 -c 1 -e compare.err -o compare.stdout -f compare.cmd
  Running (#1) 458.sjeng ref base jdr default
/home/pi/cpu2006-1.2/bin/specinvoke -d /home/pi/cpu2006-1.2/benchspec/CPU2006/458.sjeng/run/run_base_ref_jdr.0001 -e speccmds.err -o speccmds.stdout -f speccmds.cmd -C -q
/home/pi/cpu2006-1.2/bin/specinvoke -E -d /home/pi/cpu2006-1.2/benchspec/CPU2006/458.sjeng/run/run_base_ref_jdr.0001 -c 1 -e compare.err -o compare.stdout -f compare.cmd
  Running (#1) 464.h264ref ref base jdr default
/home/pi/cpu2006-1.2/bin/specinvoke -d /home/pi/cpu2006-1.2/benchspec/CPU2006/464.h264ref/run/run_base_ref_jdr.0001 -e speccmds.err -o speccmds.stdout -f speccmds.cmd -C -q
/home/pi/cpu2006-1.2/bin/specinvoke -E -d /home/pi/cpu2006-1.2/benchspec/CPU2006/464.h264ref/run/run_base_ref_jdr.0001 -c 1 -e compare.err -o compare.stdout -f compare.cmd

*** Miscompare of foreman_ref_baseline_encodelog.out; for details see
    /home/pi/cpu2006-1.2/benchspec/CPU2006/464.h264ref/run/run_base_ref_jdr.0001/foreman_ref_baseline_encodelog.out.mis
  Running (#1) 433.milc ref base jdr default
/home/pi/cpu2006-1.2/bin/specinvoke -d /home/pi/cpu2006-1.2/benchspec/CPU2006/433.milc/run/run_base_ref_jdr.0001 -e speccmds.err -o speccmds.stdout -f speccmds.cmd -C -q
/home/pi/cpu2006-1.2/bin/specinvoke -E -d /home/pi/cpu2006-1.2/benchspec/CPU2006/433.milc/run/run_base_ref_jdr.0001 -c 1 -e compare.err -o compare.stdout -f compare.cmd
  Running (#1) 470.lbm ref base jdr default
/home/pi/cpu2006-1.2/bin/specinvoke -d /home/pi/cpu2006-1.2/benchspec/CPU2006/470.lbm/run/run_base_ref_jdr.0001 -e speccmds.err -o speccmds.stdout -f speccmds.cmd -C -q
/home/pi/cpu2006-1.2/bin/specinvoke -E -d /home/pi/cpu2006-1.2/benchspec/CPU2006/470.lbm/run/run_base_ref_jdr.0001 -c 1 -e compare.err -o compare.stdout -f compare.cmd
  Running (#1) 482.sphinx3 ref base jdr default
/home/pi/cpu2006-1.2/bin/specinvoke -d /home/pi/cpu2006-1.2/benchspec/CPU2006/482.sphinx3/run/run_base_ref_jdr.0001 -e speccmds.err -o speccmds.stdout -f speccmds.cmd -C -q

482.sphinx3: copy 0 non-zero return code (exit code=127, signal=0)


****************************************
Contents of an4.err
****************************************
FATAL_ERROR: "mdef.c", line 427: Duplicate base phone: +BREATH+   -   - - filler    0      0      1      2 N


****************************************
```

**Comment by regehr** [comment] 2016-12-11 01:24
I configued CompCert like this:

```
./configure  arm-eabihf
```

and I'm building SPEC using these flags:

```
-fbitfields -fstruct-passing -flongdouble
```

**Comment by xavierleroy** [comment] 2016-12-11 10:59
Dear John, thanks for your feedback.  I don't have access to SPEC 2006 sources and don't want to go through hoops to get it, but our AbsInt colleagues might have access already.  This said, there is a smoking gun in your message:
> I see very similar mismatches when compiling the benchmarks with GCC 4.9.2 and GCC 6.2.1

Did you inform the GCC people as well?

**Comment by regehr** [comment] 2016-12-11 16:10
Hello Xavier, I have not yet reported this to the GCC people since I'm not yet sure what to say. I will investigate further and report back here if I learn anything interesting. Thank you!

**Comment by m-schmidt** [comment] 2016-12-12 14:45
Our University has access to the Spec sources. I will look into this sometime this week.

**Comment by regehr** [comment] 2016-12-13 05:00
I fixed some undefined behaviors in h264ref and the problems there seem to have gone away. However, UBSan has found no obvious undefined behaviors in sphinx3 and the problems remain. I'll keep looking...

**Comment by m-schmidt** [comment] 2016-12-15 14:34
I seem to be unable to properly install the Spec (we only have v1.1 here) on an Raspberry Pi (Perl and other tools break on all ends).

**Comment by regehr** [comment] 2016-12-15 16:24
I have v1.2 of the benchmarks and still had to do some random hacks to get the tools to build. I'll keep working on this in the background.

**Comment by bschommer** [comment] 2017-06-22 06:49
I have seen that the 2017 version of the benchmarks is available, maybe they have fixed the problems?

**Comment by regehr** [comment] 2017-06-22 15:05
I'll let you know once we get a copy of the new version.

**Comment by peizhaoo** [comment] 2017-10-15 07:51
I am late to this discussion, but I came across with the same problem when running on some ARMv8 board with Clang/LLVM. Here's what I found out that might help others who come across the same problem.

Those two benchmarks require char variables to be unsigned by default, according to this link (https://www.spec.org/cpu2006/Docs/faq.html). Also, it looks like on ARM linux, the default for char variables is unsigned, according to some online answers I found (https://stackoverflow.com/questions/3728045/any-compiler-which-takes-char-as-unsigned). And that inconsistency generates incorrect code.

For GCC/Clang, you can use the "-fsigned-char" switch  to override the defaults. Here's an example configuration I found for ARM64 that may also help (https://github.com/sjp38/CPU2006-Express/blob/master/config/linux64-arm64-gcc.cfg). It does fix the problem on my side.

**Comment by xavierleroy** [comment] 2017-10-15 15:27
@peizhaoo : thnak you very much for your remark, I would not have guessed that the problem is in the SPEC 2006 benchmark itself (it is not portable to assume `char` is signed) rather than in CompCert.  Indeed, `char` is signed on x86 (32 and 64 bits) but unsigned on ARM, PowerPC and RISC-V, according to the ABIs for these platforms. 

We should consider whether to add `-fsigned-char` and `-funsigned-char` options to CompCert.  (I am against, because properly written C code uses `signed char` and `unsigned char` where signedness matters.)  In the meantime, I'll close this issue.

**Closed by xavierleroy** 2017-10-15 15:27 UTC

**Comment by regehr** [comment] 2017-10-15 15:31
Yes, thanks for tracking this down!

I can tell you that this isn't the only broken thing in the SPEC CPU code....

**Comment by regehr** [comment] 2017-10-15 15:32
In the meantime I have SPEC CPU 2017 now and should see if these issues persist. But I will not do this in the near future due to traveling for the next 1.5 weeks or so.

**Comment by ldano** [comment] 2018-07-11 14:25
Anyone got a good config to run on ARM GCC?  I am using Spec 2017 and it's just not outputting correctly using the example config supplied.
