### ISSUE TITLE
Difference in code generated by CompCert and by Clang

### ISSUE THREAD

**Issue by aseems2007** [AbsInt/CompCert#240] opened 2018-07-04 07:38 UTC
Hi,
We have found a potential bug in O2 optimized output of CompCert compiler, can someone here direct us how to file a bug report for the same.

Thanks

**Comment by m-schmidt** [comment] 2018-07-04 11:22
You can file it right here. Or send an email to info@absint.com.

**Comment by aseems2007** [comment] 2018-07-06 08:07
Hi,
So, following is our observation:
On compiling is_sbox function of vpr benchmark (in SPEC CINT2000 benchmarks) with O2 flag, the generated code is not equivalent to LLVM IR representation of the function. We recon it incorrectly generates "idiv" instruction in place of "div".

Thanks.

**Comment by bschommer** [comment] 2018-07-06 08:21
Could you please provide a little bit more details:
* The target you are using
* The CompCert version you are using
* What target toolchain you are using (gcc version etc.)

Furthermore it would be helpful if you could provide us with a minimal example that exhibits the potential bug so that we can reproduce it.

**Comment by xavierleroy** [comment] 2018-07-08 20:22
Is this the function in question?  http://www.ece.ubc.ca/~eddieh/vpr6_dox/d1/dbf/rr__graph2_8c.html#a66b29caedf9c65c31c2c579437dd99d9

**Comment by bsorav** [comment] 2018-07-09 03:36
- We are using compcert-2.5
- Target specified as configure script command-line param: ia32-linux
- Command line options to ccomp:  -fvararg-calls -fno-fpu -funprototyped -fstruct-return -fno-tailcalls -L compcert-2.5-install/lib/compcert
- Target toolchain we are using: gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3).  We can provide the full gcc configuration if required.
-  SPEC CINT2000's 175.vpr version: 109. benchspec version: 1.3

Please let us know if you need more information from us. FYI: this issue was discovered through our research prototype tool for checking equivalence across LLVM IR and x86 binaries reported in the following paper: http://www.cse.iitd.ernet.in/~sbansal/pubs/sat18.pdf

Thanks.

**Comment by bsorav** [comment] 2018-07-09 03:47
@xavierleroy: it is the same function but it seems we have a slightly different version with different variable names, etc.  I don't know if that would make any difference though.  I can share with you our version if that helps.

**Comment by m-schmidt** [comment] 2018-07-09 07:19
I believe the problematic line is 1309 in `rr_graph2.c`:

     else {    /* Is a longline */
        seg_offset = (seg_num + chan_num - start + above_or_right) % (length + 1);
     }

All variables are of type `int` except `above_or_right` which is `boolean`, a typedef to an `enum`:

    #ifndef TRUE       /* Some compilers predefine TRUE, FALSE */
    typedef enum {FALSE, TRUE} boolean;
    #else
    typedef int boolean;
    #endif

    // Note: on my system the typedef to the enum is active

Since CompCert treats enums as of type `int`, the whole expression is of type `int` and the signed division instruction is correct.

[GCC](https://gcc.gnu.org/onlinedocs/gcc/Structures-unions-enumerations-and-bit-fields-implementation.html#Structures-unions-enumerations-and-bit-fields-implementation) (and probably clang also) treats enums as of type `unsigned int` when no negative values appear. For them the whole expression is therefore of type `unsigned int` and the unsigned division is also correct.

It seems that none of the compilers is wrong.

**Comment by bsorav** [comment] 2018-07-09 07:34
Does that mean that arithmetic operations on enums constitute unspecified or implementation-defined behaviour?  I just browsed through the C standard, but did not find anything to this effect in my quick scan of the sections on unspecified/implementation-defined behaviour.

**Comment by bschommer** [comment] 2018-07-09 07:52
See §6.7.2.2p4:

> Each enumerated type shall be compatible with char, a signed integer type, or an
> unsigned integer type. The choice of type is implementation-defined, but shall be
> capable of representing the values of all the members of the enumeration. The
> enumerated type is incomplete until after the } that terminates the list of enumerator
> declarations.

Yes the choice is implementation defined.

**Comment by bsorav** [comment] 2018-07-09 07:53
Okay, I see it in C11 6.7.2.2 (as also referenced by the GCC online doc that you pointed to).

Thanks for the clarification.

I am left wondering why the C designers chose to leave this implementation-defined.  May be so much cleaner to just define it to be "signed char/short/int"; and "unsigned char/short/int" if the corresponding signed counterpart cannot represent all values.

This ambiguity (or unspecification) is an unnecessary enemy of verification and understandability AFAICT.

**Comment by xavierleroy** [comment] 2018-07-09 14:19
@m-schmidt: thanks a lot for the detective work!

@bsorav: be very careful before concluding that differences found by your tool imply that one of the compilers is buggy.  There are significant amounts of nondeterminism in C (implementation-defined behaviors, differences in evaluation order) that can explain why both compilers are correct, as in the current example.  

Also, I'm not sure your tool accounts for optimizations that depend on the results of static analyses.  Consider:
```
int mydiv(int x, int y) 
{ if (x >= 0 && y > 0) return x / y; else return -1; }
```
The division is signed, but could be compiled into an unsigned division instruction (if it's faster), because it is known from the context that the arguments are nonnegative.  This kind of reasoning is hard to capture in a validation tool like yours.

**Comment by xavierleroy** [comment] 2018-07-09 14:20
I fixed the title of this report and will now close it.

**Closed by xavierleroy** 2018-07-09 14:20 UTC

**Comment by bsorav** [comment] 2018-07-09 14:39
To answer your question: yes our tool can correctly handle the mydiv example that you mention.  Our tool also models several types of undefined behaviour semantics in C and can handle non-determinism arising out of these types of undefined behaviour (http://www.cse.iitd.ac.in/~sbansal/pubs/hvc17.pdf).

However, modeling of unspecified and implementation-defined behaviour is indeed missing in our tool currently.

Thanks again for the clarifications.
