### ISSUE TITLE
optimisation due to undefined behaviour

### ISSUE THREAD

**Issue by fajb** [AbsInt/CompCert#208] opened 2017-11-21 11:12 UTC
Hello,

I have the following silly program undef.c  which compares a pointer and an integer.
Without optimisation, the program does nothing but prints "BAD" with optimisation.
To me, this is a case where constant propagation seems to be a bit too aggressive.
Statically, it should know that the condition &x != 0x601024 is undefined
 but prefers to return Some true and therefore predicts that the branch is always taken.
If the dataflow concludes that a condition is necessarily undef, it looks safer to not optimise the code.

#include <stdio.h>
#include <stdint.h>
int x = 5; // I know that x is allocated at address 0x601024

int main(){
  uintptr_t p = (uintptr_t) &x;
  if (p != (uintptr_t) 0x601024)
    printf("BAD %p",p);
}

Best,
--
Frédéric Besson
PS: I triggered the bug in *real* life when adding numeric assertions about pointer values that I knew should hold at runtime.

**Comment by jeehoonkang** [comment] 2017-11-21 12:32
> If the dataflow concludes that a condition is necessarily undef, it looks safer to not optimise the code.

> I triggered the bug in *real* life

In terms of the quality of implementation, maybe it'd be better for the compiler to emit a warning in this case.  However, I'd like not to characterize this translation as a bug of CompCert: it's correct in terms of both CompCert's formally defined C semantics and the ISO C standards.

**Comment by xavierleroy** [comment] 2017-11-21 18:37
@jeehoonkang is correct that this is not a bug properly speaking, but a quality of implementation issue.  

@fajb is correct that this kind of optimization of undefined behaviors is best avoided. Indeed, CompCert's value analysis and constant propagation already tries hard not to optimize on this basis.  I'll look into this particular example ASAP.

**Comment by fajb** [comment] 2017-11-22 11:12
I reported the issue (indeed not a bug) because  I am aware the design of the value analysis aims at avoiding those  situations.  I also find the issue intriguing: there is some insight about what should not happen but no formal statement...

For the case at hand,  a generic countermeasure may be something like:
Let av be the result of a sound transfer function. For any other sound abstract value av',
we have either av' <= av (the transfer function is not optimal)
                  or   av  <= av' (there is no sound incomparable value)
I think this would prevent the transfer function to make some arbitrary guess. 
For the undefined comparison of pointers, this would force the transfer function to return either bot or top.

Another related issue is that the optimisation strength is not monotonic with the result of the value analysis. In particular, if the analysis computes undef, CompCert wisely does not perform optimisations.
However, we know that this is not wise to compute the most aggressive transfer function. 
This look contradictory... Or would it be best to compute both?

CompCert could indeed emits a warning when it detects that the code has for sure an undefined behaviour. I guess I would be glad to get such feedback - I get that localising the error would not be easy; I am also not aware of any C compiler implementing this feature.

**Comment by xavierleroy** [comment] 2017-11-22 16:38
Proposed workaround in pull request #209, please review and comment.

**Comment by xavierleroy** [comment] 2017-11-24 09:04
Fixed by commit 12f7b21.  @fajb's ideas for more proofs are being discussed privately.

**Closed by xavierleroy** 2017-11-24 09:04 UTC
