### ISSUE TITLE
ia32-cygwin build stops at CminorSel.v, ndfun.ml

### ISSUE THREAD

**Issue by ludwigschreier** [AbsInt/CompCert#149] opened 2016-11-06 09:00 UTC
Hello,
any ideas why this is happening while building the ia32-cygwin version?

```
$ ./configure ia32-cygwin
Testing assembler support for CFI directives... yes
Testing Coq... version 8.5pl3 -- good!
Testing OCaml... version 4.02.3 -- good!
Testing OCaml .opt compilers... yes
Testing Menhir... version 20160825 -- good!
Testing GNU make... version 4.2.1 (command 'make') -- good!

CompCert configuration:
    Target architecture........... ia32
    Hardware model................ sse2
    Application binary interface.. standard
    Composite passing conventions. arguments: ints, return values: ref
    OS and development env........ cygwin
    C compiler.................... gcc -m32
    C preprocessor................ gcc
    Assembler..................... gcc
    Assembler supports CFI........ true
    Assembler for runtime lib..... gcc -m32 -c
    Linker........................ gcc
    Math library.................. -lm
    Binaries installed in......... /usr/local/bin
    Runtime library provided...... true
    Library files installed in.... /usr/local/lib/compcert
    Standard headers provided..... true
    Standard headers installed in. /usr/local/lib/compcert/include
    Build command to use.......... make

If anything above looks wrong, please edit file ./Makefile.config to correct.
```
...
```
COQC ia32/Op.v
COQC backend/CminorSel.v
ocamlopt -o tools/ndfun str.cmxa tools/ndfun.ml
** Error: Sys_error("tools/ndfun: No such file or directory")
File "caml_startup", line 1:
Error: Error during linking
make[1]: *** [Makefile:176: tools/ndfun] Error 2
make[1]: Leaving directory '/cygdrive/c/Users/ludwigschreier/compcert-2.7.1'
make: *** [Makefile:122: all] Error 2
```

Kind regards,
Ludwig

**Comment by bschommer** [comment] 2016-11-07 21:27
I'm not sure why this fails and I'm not really a big cygwin expert. I would suggest just compiling the tools/ndfun by hand (maybe adding .exe?) before executing the make.

**Comment by xavierleroy** [comment] 2016-11-08 08:10
Do you know which versions of ocamlopt and flexlink are used?  Those from Cygwin or those from a non-Cygwin installation of OCaml?  You can check this using `which ocamlopt` and `which flexlink`.

**Comment by ludwigschreier** [comment] 2016-11-08 19:58
Hello,

```
$ which ocamlopt
/home/ludwigschreier/.opam/4.02.3+mingw64c/bin/ocamlopt

$ ocamlopt -v
The OCaml native-code compiler, version 4.02.3
Standard library directory: C:/OCaml64/home/ludwigschreier/.opam/4.02.3+mingw64c/lib/ocaml

$ which flexlink
/usr/local/bin/flexlink

$ flexlink --version
C:\OCaml64\usr\local\bin\flexlink.exe: unknown option '--version'.
FlexDLL version 0.35alpha

```

Coq installed via _coq-installer-8.5pl3-win64.exe_

BR

**Comment by ludwigschreier** [comment] 2016-11-09 07:30
Updates.
I started make from the cmd-shell now, which seems to not run into the same issue:

```
...
COQC backend/CminorSel.v
ocamlopt -o tools/ndfun str.cmxa tools/ndfun.ml
Preprocessing ia32/SelectOp.vp
COQC driver/Compopts.v
COQC ia32/SelectOp.v
...
```

```
...
Microsoft Windows [Version 10.0.10586]

> which ocamlopt
/usr/bin/ocamlopt

> which flexlink
/usr/bin/flexlink
...

```

OK, I then ran into a problem asking for ocamlfind, which I resolved with a PATH setting, but there is a new stopper:

```
...
OCAMLOPT driver/Driver.ml                                                                     
Linking ccomp                                                                                 
File "_none_", line 1:                                                                        
Error: Files C:/OCaml64/home/ludwigschreier/.opam/4.02.3+mingw64c/lib/menhirLib/menhirLib.cmx 
       and /usr/lib/ocaml/stdlib.cmxa                                                         
       make inconsistent assumptions over implementation Sys                                  
make[2]: *** [Makefile.extr:82: ccomp] Error 2                                                
make[2]: Leaving directory '/cygdrive/c/Users/ludwigschreier/compcert-2.7.1'                  
make[1]: *** [Makefile:146: ccomp] Error 2                                                    
make[1]: Leaving directory '/cygdrive/c/Users/ludwigschreier/compcert-2.7.1'                  
make: *** [Makefile:124: all] Error 2                                                         
...
```

**Comment by bschommer** [comment] 2016-11-09 07:52
The problem you encounter is that you are using two different ocaml installations intermixed to build CompCert, the one installed under `/usr/bin` which I guess is the one offered by cygwin and the one in `C:/OCaml64/home/ludwigschreier/.opam/4.02.3+mingw64c/ ` which is compiled by opam.

**Comment by bschommer** [comment] 2016-11-30 09:51
Is this still an issue?

**Comment by ludwigschreier** [comment] 2016-12-01 09:54
Pending on my side, I relocated house, will report again shortly. KR

**Comment by bschommer** [comment] 2017-02-10 12:30
I'm closing this issue for now since the problem is not really a CompCert problem and seems to me more of a problem of cygwin, etc.

**Closed by bschommer** 2017-02-10 12:30 UTC

**Comment by ludwigschreier** [comment] 2017-02-10 12:45
Totally agree Bernard, I need a fresh Cygwin setup. KR
