### ISSUE TITLE
Build failures on Fedora 29

### ISSUE THREAD

**Issue by nemequ** [AbsInt/CompCert#281] opened 2019-03-23 19:09 UTC
I'm trying to build on Fedora 29; AFAICT the dependencies are good:

```
$ rpm -q ocaml-menhir-devel coq ocaml
ocaml-menhir-devel-20181006-1.fc29.x86_64
coq-8.7.1-7.fc29.x86_64
ocaml-4.07.0-2.fc29.x86_64
```

After configuring for the x86_64-linux target, during compilation I get:

```
OCAMLOPT driver/Version.ml
don't know what to do with +a-4-9-27
Usage: ocamlopt <options> <files>
Options are:
...
```

I managed to work around that with

```diff
diff --git a/Makefile.extr b/Makefile.extr
index a1c2ef7c..56b3858f 100644
--- a/Makefile.extr
+++ b/Makefile.extr
@@ -49,7 +49,7 @@ INCLUDES=$(patsubst %,-I %, $(DIRS))
 
 # Control of warnings:
 
-WARNINGS=-w +a-4-9-27 -strict-sequence -safe-string -warn-error +a #Deprication returns with ocaml 4.03
+WARNINGS=-w -strict-sequence -safe-string -warn-error +a #Deprication returns with ocaml 4.03
 extraction/%.cmx: WARNINGS +=-w -20-27-32..34-39-41-44..45
 extraction/%.cmo: WARNINGS +=-w -20-27-32..34-39-41-44..45
 cparser/pre_parser.cmx: WARNINGS += -w -41
```

But then I ran into

```
OCAMLC   cparser/pre_parser.mli
File "cparser/pre_parser.mli", line 114, characters 10-56:
Error: Unbound module MenhirLib
```

Which I "fixed" with by changing `MENHIR_INCLUDES` in `Makefile.config` from `-I` to `-I +menhirLib`

I'm not confident about either fix being correct (which is why I'm filing an issue not a PR), but perhaps someone familiar with building OCaml applications could get it working out of the box.

**Comment by xavierleroy** [comment] 2019-03-25 08:24
The first error is very surprising: the `-w` option to `ocamlopt` does take an argument!

If you still have the build around, could you please try
```
rm -f driver/Version.cmx
make -f Makefile.extr -n driver/Version.cmx
```
so that we see the exact invocation of `ocamlopt` that is done?

In the meantime I'll try to find a Fedora 29 VM to reproduce the issue.

**Comment by xavierleroy** [comment] 2019-03-25 08:52
I reproduced the issue.  It is indeed a problem with `MENHIR_INCLUDES` being incorrect, because
```
ocamlopt ... $(MENHIR_INCLUDES) -w +a-4-9-27
```
expands to
```
ocamlopt ... -I -w +a-4-9-27
```
and the `-I` option "eats" the `-w` option...

Why is MENHIR_INCLUDES incorrect?  Very likely because
* Menhir has two ways to install its runtime libraries, with or without the ocamlfind library manager
* The OPAM package for Menhir (the one we use for testing and most if not all CompCert users use) follows the "with ocamlfind" path
* The Fedora package for Menhir libs apparently doesn't go through ocamlfind (it's not one of its dependencies)
* The part of CompCert's configure that tries to deal with Menhir-without-ocamlfind is wrong because it hasn't been tested enough.

I'm not sure what the best fix is: debug the configure file or make it simpler by requiring ocamlfind.

**Comment by xavierleroy** [comment] 2019-03-25 08:57
PS.  If ocamlfind is installed before Menhir libs, the problem goes away:
```
yum remove ocaml-menhir-devel
yum install ocaml-findlib
yum install ocaml-menhir-devel
```
This way you can work around the issue.

**Comment by xavierleroy** [comment] 2019-03-25 09:11
Digging further, I think the problem is with the `ocaml-menhir-devel` package of Fedora.  

Fedora compiles Menhir with ocamlfind support activated:
```
[root@fedora-29]# menhir --suggest-ocamlfind
true
```
However, ocamlfind is not a dependency of `ocaml-menhir-devel`, so if ocamlfind  is not there, Menhir gets confused:
```
[root@fedora-29]# menhir --suggest-menhirLib
sh: ocamlfind: command not found
```
That's how we end up with a bad `-I` option in CompCert.

On CompCert's side I'll harden the configure script to detect this issue and emit an error. 

I really think the Fedora package is missing a dependency `ocaml-menhir-devel : ocaml-findlib`.

**Comment by xavierleroy** [comment] 2019-03-25 13:02
See 1df887f5 for a hardened configure script that detects and reports the problem.

I think this is the best we can do on CompCert's side, so I'm closing this issue.

**Closed by xavierleroy** 2019-03-25 13:02 UTC

**Comment by nemequ** [comment] 2019-03-26 00:48
Thanks for digging into this and coming up with solutions so quickly, I really appreciate it :)

I filed a bug for the packaging issue at [RH BZ #1692434](https://bugzilla.redhat.com/show_bug.cgi?id=1692434).
