### ISSUE TITLE
Fatal error: exception File "ia32/Asmexpand.ml", line 190, characters 5-11: Assertion failed

### ISSUE THREAD

**Issue by zhendongsu** [AbsInt/CompCert#110] opened 2016-08-07 00:02 UTC
The following test case causes CompCert 2.7 to have a fatal error: 

$ ccomp-2.7 small.c
Fatal error: exception File "ia32/Asmexpand.ml", line 190, characters 5-11: Assertion failed
...
$
$ cat small.c
volatile long long a;
unsigned b;

int main ()
{ 
  a = b;
  return 0;
}
$

**Comment by bschommer** [comment] 2016-08-07 13:19
The issue is fixed in release 2.5.1.

**Closed by bschommer** 2016-08-07 13:19 UTC

**Comment by Blaisorblade** [comment] 2016-08-08 15:14
Out of curiosity I looked up the fix, it should be https://github.com/AbsInt/CompCert/commit/4c7650c3eaf4dfbe5971864bf084e76f844051ee, and the failed assertions are in e.g. https://github.com/AbsInt/CompCert/blob/master/ia32/Asmexpand.ml.

**Comment by m-schmidt** [comment] 2016-08-08 16:50
Yes, the problem was caused by partial constant propagation of split 64bit values (implemented as 32bit register pairs). In the example above 'b' is converted into a 64bit value and the upper 32bits of the result are always zero.

**Comment by Blaisorblade** [comment] 2016-08-08 17:10
Ah right, `long long` was mentioned here as painful to support: http://blog.regehr.org/archives/1052

But thanks for the clarification and sorry for the spam, I'll shut up!
