### ISSUE TITLE
"make clean" does not remove MenhirLib/*.vo*

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#376] opened 2020-11-27 15:08 UTC
In CompCert v3.8, "make clean" does not remove MenhirLib/*.vo*.
I believe that it should do so.

**Comment by xavierleroy** [comment] 2020-12-11 18:25
The only way I could reproduce the issue is as follows:
- configure without `-use-external-MenhirLib`
- `make`
- re-configure with `-use-external-MenhirLib`
- `make clean`

At this point, CompCert just ignores what's in `./MenhirLib/`, since it was instructed to use an already-installed version of MenhirLib.  Hence the `MenhirLib/*.vo` files generated in the first `make` are not removed.

I don't think this is wrong.  `make clean` is designed to be run at the *end* of a build, not at the *beginning* of a build, just after `configure`.

If my analysis is wrong, please tell me.  Otherwise I'll close this issue.

**Comment by xavierleroy** [comment] 2020-12-31 13:58
I'm taking the liberty to close this report.  Feel free to reopen with additional information if my explanation above is wrong.

**Closed by xavierleroy** 2020-12-31 13:58 UTC
